# curl 'https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/profiles?select=*'
#-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
#-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
GET https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/profiles?select=*
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE

###


# curl 'https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/applets?select=*'
#-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
#-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
GET https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/applets?select=*
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE

###

# curl 'https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/stories?select=*'
#-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
#-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
GET https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/stories?select=*
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE

###

# curl 'https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/followers?select=*'
#-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
#-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE"
GET https://hdteznxiiggtdzpfsmkx.supabase.co/rest/v1/followers?select=*
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdGV6bnhpaWdndGR6cGZzbWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1NDk1NzcsImV4cCI6MTk4MDEyNTU3N30.WfqE-w-wiw1HD2y1taijIQBI6fHNnqHEbJY6OdPt5sE

###


